### ISSUE TITLE
Add support for TextScaler

### ISSUE THREAD

**Issue by MarkOSullivan94** [widgetbook/widgetbook#1037]
**Description**

> In preparation for adopting the [Android 14 nonlinear font scaling](https://developer.android.com/about/versions/14/features#non-linear-font-scaling) feature, all occurrences of textScaleFactor in the Flutter framework have been deprecated and replaced by TextScaler.

https://docs.flutter.dev/release/breaking-changes/deprecate-textscalefactor

**Expected Behavior**

`text_scale_addon.dart` is updated with the necessary changes

**Useful Resource**

https://github.com/flutter/flutter/pull/128522

**Comment by YoussefRaafatNasry** [comment]
Hello @MarkOSullivan94 👋 
Although this is a good suggestion, I don't think we will be able to do so anytime soon due to backward computability issues.
Currently the minimum Flutter version that Widgetbook supports is [3.7.0](https://github.com/widgetbook/widgetbook/blob/950d167ec23ab92ca096d5b20fd29cb099a537d5/packages/widgetbook/pubspec.yaml#L15-L16). And with the upcoming Widgetbook 4, the minimum version will be 3.10.0. As this API will only be available in Flutter versions after 3.13.0, then it cannot be added to the main package of Widgetbook. We can add it as an addon in a separate package later on, or it can be added as a [custom addon](https://docs.widgetbook.io/addons/custom-addon). But for now I will close this issue.
