### ISSUE TITLE
knob is not working when label contains : or } or ,

### ISSUE THREAD

**Issue by spmsana004** [widgetbook/widgetbook#1052]
**Description**
knob is not working when label contains : or } or ,

**Steps To Reproduce**

  bool _haActionKnob(BuildContext context) =>
      context.knobs.boolean(label: 'Condition: Level1', initialValue: true);

**Comment by YoussefRaafatNasry** [comment]
Hello @spmsana004 👋 
Since these values are used in encoding and decoding [fields](https://docs.widgetbook.io/field-types), they should not be used in either knob label or value. We can work on URL-encode them before we use them, but in the meantime, is there any example that you need to use exactly these values and alternatives cannot be used? For example, you can use `Condition - Level 1` instead of `Condition: Level 1`.

**Comment by yousinix** [comment]
The fix is now available in v3.9.0 🎉
