### ISSUE TITLE
Knobs : Colon in label name of an Int/double slider has side effects

### ISSUE THREAD

**Issue by MaudFarizon** [widgetbook/widgetbook#1164]
**Description**
Using colon in label name of a knobs `double.slider`or `int.slider` breaks the slider. When changing the slider value, the UI is not refreshed.

**Steps To Reproduce**

Use following code :
```Dart
    final double percentage = context.knobs.double.slider(
      label: 'percentage : ',
      max: 100,
      initialValue: 40,
    );
```
When changing the slider value, the UI is not refreshed. But the url changes : 
`http://localhost:60272/#/?path=widgets/templates/image-header-template&knobs={percentage+::42.18605235254705}`
You can see in the url the `::`, I guess it is the source of the problem.

The same example, just whithout the colon works fine
```Dart
    final double percentage = context.knobs.double.slider(
      label: 'percentage ',
      max: 100,
      initialValue: 40,
    );
```

**Expected Behavior**
Possibility to define the label with a colon

**Additional Context**
I reproduced with widgetbook version 3.7.1, and Flutter 3.19.5

**Comment by YoussefRaafatNasry** [comment]
Hello @MaudFarizon 👋 
Thanks for reporting this!

This is happening due to the way we encode/decode `Field`s (that are used in both addons and knobs).
The following line is causing the issue

https://github.com/widgetbook/widgetbook/blob/650b2cd17dbd3c97a7862ad049cf9ec39824d012/packages/widgetbook/lib/src/fields/field_codec.dart#L41

A possible fix would be to use URL encoding/decoding on `Field`'s labels before doing the group encoding/decoding.
It might be a quick fix, do you want to work on a PR for that?

**Comment by YoussefRaafatNasry** [comment]
PR #817 is relevant to the fix, as it was solving the same problem but with string knob values (not labels).

**Comment by MaudFarizon** [comment]
Ok thanks, I will give it a try :)
