### ISSUE TITLE
Widgetbook version 4.0.0

### ISSUE THREAD

**Issue by mjablecnik** [widgetbook/widgetbook#1215]
Hello, my question is about widgetbook version 4.0.0
I see in pub.dev was released some alpha version 6 months ago but now it looks there is not any progress.
My question is: Why? And when do you want to release next stable version 4.0.0?

![Screenshot 2024-07-25 at 21 58 42](https://github.com/user-attachments/assets/1dde6266-20a6-4b95-911e-48c42ba0cf36)

**Comment by jenshor** [comment]
Hey @mjablecnik, that's a great question! 

In the last year, [we got plenty of feedback from the community](https://github.com/widgetbook/widgetbook_4?tab=readme-ov-file#why) and with the very early alpha version of Widgetbook 4, we wanted to try out some of these changes for early adopters. 

While the alpha provided additional feedback on how Widgetbook can improve, fully implementing all the features would have been a lot of work with significant changes to your workflow and unavoidable migrations. Since we also faced the upcoming launch of macros, we decided to wait to make adjustments and to reevaluate once macros launched. 

We will soon pick up Widgetbook 4 again. If you would like to provide additional feedback and steer the direction of Widgetbook 4, please have a look at our [playground repository](https://github.com/widgetbook/widgetbook_4).

General feedback is also always welcome!

**Comment by mjablecnik** [comment]
@jenshor Thank you for your response. 
I wrote one feedback here: https://github.com/widgetbook/widgetbook_4/issues/1

**Comment by yousinix** [comment]
I will be closing this issue, as it is more of a question than a bug or feature request.
Consider using [our Discord](https://discord.com/channels/879618555560218625/927145129377140796) or [GitHub Discussions](https://github.com/widgetbook/widgetbook/discussions) for future questions.
