### ISSUE TITLE
`flutter_screenutil` not working properly with Widgetbook

### ISSUE THREAD

**Issue by BarneyB173** [widgetbook/widgetbook#1267]
**Description**
When add screen_utils as Builder Addon, widgetbook doesn't scalling when change the device frame at all, seemlike it always remain web the origin size.

**Steps To Reproduce**

1. Go to screen_utils example
2. Run the project using chrome
3. Changing the device frame and see the different

**Expected Behavior**
It should change the screen size according to given device frame.
https://github.com/user-attachments/assets/8d5d02c1-dc84-4bc0-b260-c68351063bbc

**Screenshots**
The device's size doesn't update.
https://github.com/user-attachments/assets/edc88faf-292f-4dbc-b62d-e12c59991b18

**Additional Context**

**Comment by yousinix** [comment]
Hello @BarneyB173 👋 
Thanks for reporting this! It seems like it's also not working without devices, something must have broken it in the last releases. We will investigate it more and let you know.

**Comment by yousinix** [comment]
I can see that this issue is only happening with `flutter_screenutil` >= 5.9.2, probably because they stopped using `MediaQuery.of` and started using `View.of` in OpenFlutter/flutter_screenutil@f7c551acd4cc82460c3a29ec5a7262d6ec678746.

Can you confirm that setting `flutter_screenutil` version to 5.9.1 solves the issue for you? We will look later into how to fix this for newer versions.

**Comment by BarneyB173** [comment]
Look like it worked with version 5.9.1, thank you for fast reply

**Comment by Mastersam07** [comment]
`flutter_screenutil: 5.9.1` works.
