### ISSUE TITLE
[version 2] Page zoom doesn't change, left menu not expandable/contractible, tools zoom and offset too much space

### ISSUE THREAD

**Issue by guillempuche** [widgetbook/widgetbook#127]
**Description**
I'm using your https://demo.widgetbook.io/#/ that has the Widgetbook `2.0`.

Three problems:
- I can't  increase or decrease page zoom. 
- I can't expand and contract the left menu (where there is the search bar and Widgetbook components)
- Tool for zooming and offsetting device frame should occupy less space (maybe it should show when you hover over it with the mouse)

**Steps To Reproduce**

1. Go to `https://demo.widgetbook.io/#/`
2. Try to zoom in or Zoom out
3. Try to expand & contract left menu.
4. Try to 

**Expected Behavior**
Font size should decrease and increase accordingly to the browser page zoom and font size.

**Screenshots**
<img width="1019" alt="imatge" src="https://user-images.githubusercontent.com/3519924/153888080-cdf89616-575a-46e7-80c0-db4c93305378.png">

**Comment by JensHor** [comment]
Do you mean the zoom functionality within widgetbook or in the browser?

**Comment by guillempuche** [comment]
Within the browser

**Comment by JensHor** [comment]
Zooming within the browser is currently not working properly for flutter web. However, this is not a widgetbook problem. The flutter team tracks the problem here: https://github.com/flutter/flutter/issues/77084. I'll close this issue for now. 

I also created a feature request for the resizable panel here: https://github.com/widgetbook/widgetbook/issues/143.
In addition, we agree that the panel for resizing and moving the render viewpoint isn't really accessible. We are planning on improving this within the next week.
