### ISSUE TITLE
Use with Bloc? 

### ISSUE THREAD

**Issue by vi1world** [widgetbook/widgetbook#1306]
Is it possible to use Widgetbook (I'm using V4 alpha 2) with Bloc? Basically, can I provide the Bloc that is needed for a widget to load in a stories.dart file? 

Thank you

**Comment by yousinix** [comment]
Hello @vi1world 👋 

There are two ways to wrap your stories with any widget (not just `BlocProvider`).

1. Single Story Setup: You can use the `setup` parameter to wrap the story as follows

    ```dart
    final $Default = MyWidgetStory(
      setup: (context, child, args) {
        return BlocProvider(
          create: () => MockedBloc(),
          child: child,
        );
      },
    );
    ```


1. Component Setup: If you have more one story for a single component, instead of passing the `setup` on each one of them, you can define a global `$setup` function as follows:

    ```dart
    // This will be used as the default `setup`
    Widget $setup(
      BuildContext context,
      Widget child,
      NumericBadgeInputArgs args,
    ) {
      return BlocProvider(
        create: () => MockedBloc(),
        child: child,
      );
    }
    
    final $Primary = MyWidgetStory();
    final $Secondary = MyWidgetStory();
    ```
    
For more info about mocking with Widgetbook, you can read our guide [here](https://docs.widgetbook.io/guides/mocking).
