### ISSUE TITLE
Include SafeArea in devices

### ISSUE THREAD

**Issue by LucasJosefiak** [widgetbook/widgetbook#165]
One user suggested:
For the class Device as well as for the predefined instances like e.g. Device.iPhone11, SafeArea should be considered. For example, the iPhone11 has a Size(828, 1792), but you can't use it completely because you still have the notch at the top and the curvature of the display at the bottom. On the iPhone11 the SafeArea is EdgeInsets.only(top: 88, bottom: 68) (at devicePixelRatio: 2.0 ). (See picture 3, this is a Golden test on an iPhone11. There the title of the AppBar ("Welcome") is further down than it is in the widgetbook (image 1/2) just because of the SafeArea due to the notch.
![image](https://user-images.githubusercontent.com/69841305/161701257-45a0e493-fbfa-42e5-ac37-d4587d9ebcc3.png)
![image (2)](https://user-images.githubusercontent.com/69841305/161701264-61a51004-86c3-467b-8e46-17d5b6474e4f.png)
![image (3)](https://user-images.githubusercontent.com/69841305/161701272-620fbf71-08ce-4def-b310-f400d1012563.png)

**Comment by sebastianbuechler** [comment]
Is this really closed? When I use version 3.2.0 and want to display a `RawButton` I get this:
![image](https://github.com/widgetbook/widgetbook/assets/42775578/2f1d7f9c-8579-4099-a4de-94bb0ca1a7ed)
But if I wrap that `RawButton` in a `SafeArea` directly in the `WidgetbookUseCase` I get the expected behavior:
![image](https://github.com/widgetbook/widgetbook/assets/42775578/12442e22-5834-4164-83a0-e76b9a3f436a)
I'm using  `Devices.ios.iPhone13` for the screenshots.

**Comment by YoussefRaafatNasry** [comment]
@sebastianbuechler, this is intentional behavior.
If you want to have a safe area, use "None" frame.
But if you don't want to have safe areas, use "Device frame".
This was by design, to allow users to have the best of both worlds when it comes to `DeviceFrameAddon`.
