### ISSUE TITLE
Unable to scroll in Widgetbook

### ISSUE THREAD

**Issue by ChrisSSocha** [widgetbook/widgetbook#173]
**Description**

Pages with a scroll view (`SingleChildScrollView`) do not scroll in Widgetbook, but work as expected when in a Flutter app.

**Steps To Reproduce**

Example scrolling widget:
```dart
class MyStatelessWidget extends StatelessWidget {
  const MyStatelessWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {

    return Center(
      child: SingleChildScrollView(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Container(
              height: 200,
              width: double.infinity,
              color: Colors.red,
            ),
            Container(
              height: 200,
              width: double.infinity,
              color: Colors.amber,
            ),
            Container(
              height: 200,
              width: double.infinity,
              color: Colors.blue,
            ),
            Container(
              height: 200,
              width: double.infinity,
              color: Colors.red,
            ),
            Container(
              height: 200,
              width: double.infinity,
              color: Colors.amber,
            ),
            Container(
              height: 200,
              width: double.infinity,
              color: Colors.blue,
            )
          ],
        ),
      ),
    );
  }
}
```

How the widget is added to the widgetbook

```dart
class HotReload extends StatelessWidget {
  const HotReload({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Widgetbook.material(
        categories: [
          WidgetbookCategory(name: "Pages", widgets: [
            WidgetbookComponent(
              name: 'Foo',
              useCases: [
                WidgetbookUseCase(
                    name: 'standard',
                    builder: (context) => const MyStatelessWidget()),
              ],
            )
          ])
        ],
        themes: [
          WidgetbookTheme(
            name: 'Light',
            data: ThemeData.light(),
          ),
          WidgetbookTheme(
            name: 'Dark',
            data: ThemeData.dark(),
          ),
        ],
        appInfo: AppInfo(name: 'Quin demo'),
        textScaleFactors: [0.5, 1.0, 2.0]);
  }
}
```

The `MyStatelessWidget` scrolls fine when added to a `MaterialApp` and run on a device.

**Additional Context**

Using `widgetbook: ^2.1.0`

Am i missing something?

**Comment by JensHor** [comment]
Thanks for raising this issue. I've tested the code and it's working for me. However, the behaviour is a bit different in comparison when one is testing on e.g. the iOS simulator. On the iOS simulator you'd scroll with mouse down (and hold + moving the mouse). On Widgetbook, you need to use the mouse scroll function (mouse wheel) to scroll up and down. In addition, you need to make sure that you are in selection mode:

<img width="710" alt="image" src="https://user-images.githubusercontent.com/16862002/166870706-4cb432a8-39bb-4aa9-a5ea-de9f0821a21d.png">

instead of move mode:

<img width="700" alt="image" src="https://user-images.githubusercontent.com/16862002/166870719-7862b1d2-b052-4c99-89ca-5cd4aa0d8f42.png">

With move mode enabled, Widgetbook will zoom instead of scroll.

**Comment by JensHor** [comment]
I'll close this issue, but if this is still not working for you, make sure to re-open so we can investigate 👍🏻

**Comment by ChrisSSocha** [comment]
Ah yes, quite right. I'm running Widgetbook on Chrome and MacOS targets, and was attempting to click-and-drag rather than using the scroll wheel. Thanks for the clarification 👍

**Comment by MarkOSullivan94** [comment]
Is there any way to enable the click-and-drag which is the default behaviour for emulated mobile devices?
