### ISSUE TITLE
How to set `disable-properties`

### ISSUE THREAD

**Issue by trunghieuvn** [widgetbook/widgetbook#251]
**Description**
I updated to version `widgetbook: ^2.4.1`

I can't see generate full param in URL.
Please help me how to enable for it.

Thanks

**Steps To Reproduce**

1. Go to ...
2. Click on ....
3. Scroll down to ....

**Expected Behavior**
A description of what you expected to happen.

**Screenshots**

**Additional Context**

**Comment by jenshor** [comment]
To use widgetbook properly it is not necessary to use the property in any way. 

We introduced the property since it was required for a feature within our premium product Widgetbook Cloud. 

However, if you describe in more detail what you are trying to do, we might be able to solve the problem you are facing.

**Comment by jenshor** [comment]
Okay, so what you'd like to do is deep linking. This feature is currently not working because of a bug. See https://github.com/widgetbook/widgetbook/issues/204. Closing this issue due to a duplicate. 

We'll likely fix the issue within the next weeks.
