### ISSUE TITLE
suggestion: custom icons for categories/folders

### ISSUE THREAD

**Issue by Xazin** [widgetbook/widgetbook#335]
**Description**
I suggest to have the option to choose a custom IconData for Categories and Folders.

The way we currently structure our Widgetbook, is that each category is for a different platform/target, and it would be nice to use custom icons to also indicate this.

It's purely a nice-to-have, I would be willing to throw in a PR for this on the 3.0 branch if I have time.

Would this make sense to have on all type of items in the menu (categories, folders, use-cases/components)?

Let me know what you think.

**Comment by jenshor** [comment]
Hi Xazin, that's a great idea. We aim to change the functionality for the widgetbook 3.0 release and look forward to including this functionality in the code. Do you have an idea on how to make this functionality accessible with the generator? I'm assuming you are using `widgetbook` without the generator.

**Comment by Xazin** [comment]
> Hi Xazin, that's a great idea. We aim to change the functionality for the widgetbook 3.0 release and look forward to including this functionality in the code. Do you have an idea on how to make this functionality accessible with the generator? I'm assuming you are using `widgetbook` without the generator. 

That is a good point, I would have to look into other code samples taking advantage of the generator to get an idea of it.

I will spend some time during this week to check it out, I am indeed using widgetbook without it at the moment.

If you have some good examples of implementations let me know and I will reference it.

**Comment by YoussefRaafatNasry** [comment]
Hello @Xazin 👋 

Although I personally liked the proposal here, but this will be technically hard to achieve since the navigation nodes (i.e. categories and folders) are shared with external tools like Widgetbook Cloud, which are not necessarily implemented in Flutter and will need extra different dependencies or logic to resolve the Icon's Unicode to a relevant icons font.

For these reasons, we will not be moving forward with this issue.
