### ISSUE TITLE
feat: Custom global properties

### ISSUE THREAD

**Issue by aloisdeniel** [widgetbook/widgetbook#363]
**Description**

Currently, a set of pre-defined properties is available :

![image](https://user-images.githubusercontent.com/7687231/203868701-c2c8c508-8697-4364-85bd-bca81170b965.png)

It would be awesome to add the possibility to create additional properties.

In addition to theme brightness, my app has different variants: sound enabled/disabled, haptic feedback mode, visual animation enabled/disabled...

**Proposal**

Something like the knobs would be perfect:

```dart
return Widgetbook<AppBrightnessVariant>(
      appInfo: AppInfo(
        name: 'Clickup | Flutter UI',
      ),
     appBuilder: (context, child) => AppSoundEnabled(
         enabled: context.properties.boolean(label: 'Sound'),
         child: child,
     ),
     /// ...
);
```

**Comment by jenshor** [comment]
Hey Aloïs, thanks for opening this feature request. Since we've been unhappy about the whole property implementation, we are currently working on a fully customizable properties panel. 

We will likely provide so-called Add-ons that allow for theming, text scales, locales, etc. 
For instance, themes will be accessible via `context.materialTheme` or `context.theme<T>()` (for custom themes e.g. the theme used in your Asgard shop app).

Since we are already in the middle of implementing this feature, you can expect a release soon 🎉

**Comment by aloisdeniel** [comment]
That's awesome! Thank you

**Comment by jenshor** [comment]
Sorry that this took way longer than expected. We completely refactored our architecture to support `AddOn`s. This enables developers to inject their own global properties into Widgetbook. The implementation is almost done we just have to refine the API a bit to make it easier to use. 

Looking forward to ship this feature soon!
