### ISSUE TITLE
Color Knob

### ISSUE THREAD

**Issue by mbtodorov** [widgetbook/widgetbook#368]
# Proposal: knobs for colors

## Description
As a developer, I want to be able to leverage knobs to specify a Widget's constructor parameter of type `Color`. The API can be reminiscent of other knobs:

```dart
Icon(
  Icons.thumbs_up_sharp,
  color: context.knobs.color(
    label: 'Color of the icon'
    initialValue: Colors.red,
  ),
)
```

The signature of the `color` method (inside `KnobsBuilder`) can be:
```dart
bool color({
  required String label,
  String? description,
  Color? initialValue,
});
```

In terms of how the knob would reflect on the UI, it can use something like this open source package https://pub.dev/packages/flutter_colorpicker, or perhaps a custom implementation. But the gist is that users would be able to change the color of a widget using knobs.

## Rate the proposal

Make sure to hit 👍🏻 if you'd like to see this implemented soon.

Make sure to hit 👎🏻 if you think this proposal is a bad idea.

**Comment by mbtodorov** [comment]
If anyone else is looking for a similar functionality in the meantime, this workaround is possible:

```dart

const _kFallbackColor = 0xFFFF0000;

extension on String {
  Color asColor() {
    if (length != 7) {
      return const Color(_kFallbackColor);
    }
    return Color(int.tryParse(replaceFirst('#', '0xFF')) ?? _kFallbackColor);
  }
}

extension on Color {
  String get hexString =>
      '#${value.toRadixString(16).substring(2, 8).toUpperCase()}';
}

Color colorKnob(
  BuildContext context, {
  required String label,
  required Color initialValue,
}) {
  return context.knobs
      .text(
        label: label,
        description: "Must be a valid hexadecimal color prefixed with '#'. "
            "Defaults to a red color if the value can't be parsed.",
        initialValue: initialValue.hexString,
      )
      .asColor();
}
```

The `colorKnob` function can be used as follows:
```dart
WidgetbookUseCase(
  name: 'elevated',
  builder: (context) => Icon(
    Icons.thumb_up_sharp,
    color: colorKnob(
      context,
      label: 'Color',
      initialValue: Colors.blue,
    ),
  ),
),
```

Unfortunately you can't use an `extension` to make the API more reminscent of the other knobs (i.e `context.knobs.color`), since the `KnobsBuilder` is an abstract class and dart doesn't support `extension`s on abstract classes.

The results:
<img width="600" src="https://user-images.githubusercontent.com/25320807/205438581-31b805a5-c147-4115-8a10-b56142c18f36.gif" />

**Comment by jenshor** [comment]
Love the proposal! I'll add some requirements so that we can start with the implementation. [We already got a basic color knob implemented](https://github.com/widgetbook/widgetbook/blob/main/packages/widgetbook_core/lib/src/settings/features/knobs/color_knob.dart) but it's not yet feature complete. 

## Requirements

### Color spaces
The following color spaces should be supported: 
- Support for hexadecimal colors (including alpha value) 
    - Input validation
    - [Optional] Color picker (should not depend on additional packages)
- Support for RGBA (RGB + Alpha value)
    - Input validation
    - [Optional] Color picker (should not depend on additional packages)
- Support for HSL (Hue, Saturation, Lightness)
    - Input validation 
    - [Optional] Color picker (should not depend on additional packages
### Preview
<img width="225" alt="image" src="https://user-images.githubusercontent.com/16862002/217270750-18cc688b-d253-4578-8313-27baf0132c83.png">

A small color preview would be nice (see figma screenshot)

### Testing
- 100% test coverage for the whole widget

### Design
- Should be based on Material 3

### Usage

```
Icon(
  Icons.thumbs_up_sharp,
  color: context.knobs.color(
    label: 'Color of the icon'
    initialValue: Colors.red,
    initialColorSpace: ColorSpace.rgba,
  ),
)
```

**Parameters:**
| Property          | Description                                                      | Required | Default value  |
|-------------------|------------------------------------------------------------------|----------|----------------|
| label             | Unique label, used to update the knob                            | Yes      | -              |
| initialValue      | The color that is preselected, when the use-case is loaded       | Yes      | -              |
| initialColorSpace | The color space that is preselected, when the use-case is loaded | No       | ColorSpace.hex |
| description       | The description of what the knob is doing                        | No       | -              |

**Comment by YoussefRaafatNasry** [comment]
We currently have a Color knob, but we need to add the "Color Space" field to it.

**Comment by francescovallone** [comment]
Can you assign it to me? I would love to work on this feature! 🙂

**Comment by francescovallone** [comment]
Hello! I'm just passing by to give you a small update about this feat. 😄

- I worked on the ColorSpace implementation and right now, as requirements, hex (with and without alpha), rgba and hsl are supported.
- A small preview of the color is showed in the same row as the DropdownButton for the ColorSpace
- Every color space has its own TextFormFields.

Here is a small preview for all the ColorSpaces.

RGBA:
![rgba](https://github.com/widgetbook/widgetbook/assets/15020233/a5b88b4d-407a-4e81-b5d5-dbd197cb7956)

HEX without Alpha values
![hex_no_alpha_string](https://github.com/widgetbook/widgetbook/assets/15020233/8861dfb0-8ff4-49ae-8dd6-e4f99420c0a7)

HEX with Alpha values
![hex_with_alpha_string](https://github.com/widgetbook/widgetbook/assets/15020233/591d03cb-3daa-4c67-9f0f-f98dfa84903d)

HSL
![hsl](https://github.com/widgetbook/widgetbook/assets/15020233/2bbf9b90-879b-4ceb-90b8-d03831c7f126)
