### ISSUE TITLE
Theme properties need to be required or have defaults

### ISSUE THREAD

**Issue by maks** [widgetbook/widgetbook#51]
When theme properties are set, I just see a "No theme defined" in the main preview window, yet the `lightTheme` and `darkTheme` properties on `Widgetbook` are not marked as `required`.
I worked around this by setting:
```
lightTheme: ThemeData.light(),
darkTheme: ThemeData.dark(),
```
But really I think they should either be set to `required` in the constructor or otherwise sensible default like the above should be used.

**Comment by JensHor** [comment]
Hi @maks 👍🏻 thanks for opening issues and giving feedback. We recently changed the behaviour of the theme properties due to an error that occurred when switching themes.

The current behaviour is intended and was purposely implemented this way. Making the properties required would be great but i think that just forces developers of single-themed apps to specify certain themes that aren't used anyways. Defaulting to a value is especially useful if you are using Widgetbook for implementing layouts and building widgets in isolation. However, we decided against a default theme because it might confuse people 'reading' the Widgetbook since UI elements are rendered different from what they should look like. 

In the end, I think it depends on what you are using Widgetbook for. Would you mind sharing what your primary use case is? 

Let me know if you have concerns regarding the argumentation provided above 😊

**Comment by maks** [comment]
Ah ok, yep that all does make sense. Its pretty obvious in the UI, but may also worth just adding a note in the Readme to highlight that setting a theme is required to use widgetbook.

As for my use case, I'm currently looking to use Widgetbook as a replacement for the [Storyboard](https://pub.dev/packages/storyboard) package, which I have been happily using for a few years now, as to me it seems Widgetbook is an evolution of it's approach, while being more feature-rich and actively developed, where Storyboard is not.
