### ISSUE TITLE
small resolution

### ISSUE THREAD

**Issue by SultanAbbas0** [widgetbook/widgetbook#615]
I've set up a device like this:
![image](https://user-images.githubusercontent.com/87972014/230748770-d2f8bac3-e764-4b4e-a159-df0199a7ae85.png)
and getting this as a result
![image](https://user-images.githubusercontent.com/87972014/230748777-a3dcdc5d-e00c-401d-abe7-700cf267fe43.png)

**Comment by jenshor** [comment]
Thanks for raising this issue. For the Device Frames, we are using the `device_frame` package that currently has a bug for the iPhone 12 (see https://github.com/aloisdeniel/flutter_device_preview/issues/191). Since the `device_frame` package is currently only sparsely maintained we are thinking of removing it as a Widgetbook dependency. If there are reasons against this, let us know. 

Since it's an issue from a dependency, I'm closing this issue.
