### ISSUE TITLE
Annotation names gone wrong

### ISSUE THREAD

**Issue by westito** [widgetbook/widgetbook#723]
In the new 3.0.0-rc.1 version the annotations were renamed by removing "Widgetbook". This was a bad idea I think because "App" and "UseCase" is very general names. For ex. in my project I have "App" main class for my app, and also have a "UseCase" base interface for clean architecure's use cases. Now I have to namespacing all widgetbook imports and prefix all annotations by it. Also importing my own classes went harder because the unambiguous namings.

**Comment by YoussefRaafatNasry** [comment]
The `@WidgetbookUseCase` annotation was causing a lot of confusion since it [also exists in `widgetbook`](https://github.com/widgetbook/widgetbook/blob/main/packages/widgetbook/lib/src/models/widgetbook_use_case.dart). So we had to weight which change might be lighter.

We currently recommend that you use the following method for importing annotations:

```dart
import 'package:widgetbook_annotation/widgetbook_annotation.dart' as widgetbook;

@widgetbook.App()
class WidgetbookApp extends StatelessWidget {
  // ...
}
```

The good news is that we are still in a release candidate, and we can changes things a bit based on the feedback we get. But this is not really likely to change since we are trying to remove code generation all along.
