### ISSUE TITLE
Ability to increase the tap target for the directories view

### ISSUE THREAD

**Issue by TahaTesser** [widgetbook/widgetbook#838]
Tap target is too small for me. This often leads to me clicking above or below items. It should be at least standard 48 pixels or add an option to adjust visual density for this view.

![Group 5](https://github.com/widgetbook/widgetbook/assets/48603081/507db527-f84f-4851-9f6e-2b7b857598e0)

**Comment by YoussefRaafatNasry** [comment]
Hello @TahaTesser 👋 
Which platform are you running Widgetbook on?
It makes sense to make the tap size bigger only if it's mobile, but Widgetbook is designed to run on desktop/web platforms, and we do not have first-class support for mobile yet.

**Comment by YoussefRaafatNasry** [comment]
IMO, Material Design is a mobile-first design system. The tap size is that big because people use their fingers on mobile devices and not pointers. Widgetbook only uses Material Design because it's built in Flutter, but we tend to have our own design decisions and we don't hardly follow the Material Design specification.

In a content-dense view, having that much spacing would result in worse UX. For example, imagine having that much spacing between your files in your editor's navigation panel. Or if [Firebase's docs](https://firebase.google.com/docs/build) side panel's items have 48px padding instead of 24px.

On the other hand, we have expand/collapse and search features to help declutter your navigation tree, and avoid misclicks.

**Comment by TahaTesser** [comment]
> In a content-dense view, having that much spacing would result in worse UX. For example, imagine having that much spacing between your files in your editor's navigation panel. Or if [Firebase's docs](https://firebase.google.com/docs/build) side panel's items have 48px padding instead of 24px.

For accessibility, there should be an option to adjust this. This doesn't need to be the default.

**Comment by TahaTesser** [comment]
Thanks for the Firebase link. It made me think about why I am not mis-clicking items there.

So I took a closer look at the Widgetbook buttons. It looks like unselected items are even smaller than 24px.  I might be clicking the other item when finding the clickable area.

![Screenshot 2023-08-16 at 15 34 44](https://github.com/widgetbook/widgetbook/assets/48603081/88e7b487-1072-4a3b-912e-f29af812a692)

**Comment by TahaTesser** [comment]
Also, notice Firebase menu items don't have gaps between clickable areas.

**Comment by YoussefRaafatNasry** [comment]
@TahaTesser The gaps were also removed in the same PR, it's out now in [v3.2.0](https://pub.dev/packages/widgetbook/versions/3.2.0), you can try it out and let us know what you think, and if it solves the original issue.

**Comment by TahaTesser** [comment]
I just tried on the `main` branch. This is much better, thanks!
