### ISSUE TITLE
Having issues with the `screen_util` example

### ISSUE THREAD

**Issue by Rohithgilla12** [widgetbook/widgetbook#876]
**Description**

Looks like the `Material` widget is not being placed.
![image](https://github.com/widgetbook/widgetbook/assets/19389850/970d4c34-663f-4d80-97c6-74895ba152b1)

Looks like `screenutil` is  behaving a bit weird too
![Kapture 2023-08-30 at 14 08 04](https://github.com/widgetbook/widgetbook/assets/19389850/366923d8-913d-48b2-9382-f4469a299098)

**Steps To Reproduce**

1. Go to https://github.com/widgetbook/widgetbook/tree/main/examples/screen_util_example
2. Run the app
3. Click on Default Screen container
4. See the behavior

**Expected Behavior**
Before the update it was working as expected, after updating to `widgetbook: 3.2.0` it is starting to behave oddly.

**Screenshots**
Attached above

**Additional Context**

**Comment by YoussefRaafatNasry** [comment]
Hello @Rohithgilla12 👋 
I will look more into it and let you know.

**Comment by Rohithgilla12** [comment]
> Hello @Rohithgilla12 👋 
> 
> I will look more into it and let you know.

I think the "Material" wrapper is missing somewhere but yes thanks 🫡

**Comment by YoussefRaafatNasry** [comment]
After digging deeper into this, we've found that ScreenUtil used the Workbench's `MediaQuery` and not the Device's. This was logically correct, since `ScreenUtilInit` was added within the `appBuilder` and not below the `DeviceFrameAddon`.

To counter this, `ScreenUtilInit` should be added as a [custom addon](https://docs.widgetbook.io/addons/custom-addon). But since this will be a lot of boilerplate for such a small thing, we have added the new `UseCaseBuilderAddon` in #880 to make your life easier.
