### ISSUE TITLE
LocalizationAddon pass onChange property

### ISSUE THREAD

**Issue by petrnymsa** [widgetbook/widgetbook#917]
**Description**
If use case or component uses localization package, such as easy_localization, there is no way to change package's locale via LocalizationAddon.

**Expected Behavior**
By looking at code, it could be solved by allow pass onChange property into `ListField` 

```dart
	// ... rest of code
  @override
  List<Field> get fields {
    return [
      ListField<Locale>(
        name: 'name',
        values: locales,
        initialValue: initialSetting,
        labelBuilder: (locale) => locale.toLanguageTag(),
        onChanged: (context, locale) => onChange(locale),
      ),
    ];
  }

// usage
 LocalizationAddonCustom(
          locales: context.supportedLocales,
          localizationsDelegates: context.localizationDelegates,
          initialLocale: context.locale,
          onChange: (locale) => locale == null ? {} : context.setLocale(locale), // setLocale comes from easy_localization package
        ),
```

**Additional Context**
I am open to create PR to solve this

**Comment by YoussefRaafatNasry** [comment]
Hello @petrnymsa 👋 

Adding the `onChange` to `ListField` won't be the best solution for this issue, since fields are also used in Widgetbook Cloud which is built in React and they cannot replicate the `onChange` logic. In fact, the `onChange` might get deprecated. 

The better solution would be to add this logic to `buildUseCase` method. I don't see us adding this to the official `LocalizationAddon`, feel free to create a [custom addon](https://docs.widgetbook.io/addons/custom-addon), with the name `EasyLocalizationAddon`, in you project.
