### ISSUE TITLE
Improve Contribution Guide 

### ISSUE THREAD

**Issue by ayan-joshi** [widgetbook/widgetbook#959]
**Description**
So , the contribution part of the Readme file is looking pretty dull , it should explain how a contribution can be make to the repository.
So I would like to help it and improve the contribution section in Readme file.

I'll add the whole process how a contributor can make contribution to the widgetbook 

**Additional Context**
Assign me this issue @YoussefRaafatNasry , so I can start working on it

**Comment by YoussefRaafatNasry** [comment]
The contribution section shouldn't be in the README but in [CONTRIBUTING.md](https://github.com/widgetbook/widgetbook/blob/main/CONTRIBUTING.md), so I would suggest you refer to that file from the README. and maybe make the section a little bit better as you've said.

**Comment by biswabaibhab007** [comment]
I think couple of changes that can be made to make the docs more understandable. Assign me this issue so that I can propose the changes..

**Comment by biswabaibhab007** [comment]
I think couple of changes that can be made to make the docs more understandable. 
Assign me this issue @YoussefRaafatNasry so that I can propose the changes..

**Comment by YoussefRaafatNasry** [comment]
@biswabaibhab007 I have assigned you along with @ayan-joshi.
You can open a PR based on #962 with these "changes" and I will see if it really adds value to the contribution guide.
Then I will merge the PRs sequentially to avoid any conflicts.

Please note that if any PRs do not really add value, they will be rejected in the review process.

**Comment by YoussefRaafatNasry** [comment]
Hello @ayan-joshi, @biswabaibhab007 👋 
We are so sorry to inform you that after several discussions with our team, we have decided not to move forward with these issue and the linked PRs (#962 & #976). This was because it violates rules 4 and 6 from our [Hacktoberfest guidelines](https://github.com/widgetbook/widgetbook/issues/918).

Both PRs do not add real value to the docs, and they are just a rephrasing of the current one we have.
Thanks a lot tho for trying to contribute! 💙 And I will be happy to see you trying again with another existing issue.
